# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Speak',
            fields=[
                ('claim', models.TextField(blank=True, null=True)),
                ('speaker', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('trans_id', models.TextField(blank=True, null=True)),
                ('claim_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'speak',
                'managed': False,
            },
        ),
    ]
